### ISSUE TITLE
API.tsx cleanup

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/monorepo#106]
**Describe the bug**
The `api.tsx` file is huge! Its very difficult to find specific functions in it. We should break it up into several files, one per `event`. One for edit events, one for api calls, etc.

**Comment by naterush** [comment]
@aarondr77 I've thought about this refactor before, and I'm not sure that breaking it up is the best bet. However, I agree that it is pretty hard to find things in it sometimes! Here's my thinking:
1. When you're looking to refactor all the functions at once (e.g. changing the event format generally), having everything in one file is really nice. 
2. If you're looking to change a single function you can just search for it - you don't need to go scrolling through this file.

The issue with (2) is that the functions have very inconsistent names. I think the best refactor of this file would be to rename functions to be consistent. Probably something like:
1. API calls are prefixed with api, edit calls are prefixed with edit, etc.
2. All of them are arranged by type, and then alphabetically within that.

If we just did that, I think we'd end up with a totally pleasant and fine file that makes sense to keep together, that isn't hard to search because it's organized. There are also some disadvantages to breaking it up - namely that it's a core class that is gonna switch in the future if we move to different environments; the more nested it is the harder it's gonna be to do this.
