### ISSUE TITLE
Signup Flow is not displayed 

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/monorepo#417]
On dev, but not main, the signup flow is not shown to me after I `rm -rf user.json`. 

https://user-images.githubusercontent.com/18709905/182167507-73f2e8ed-11f1-42fa-8ffa-59f41a98ce5c.mov

**Comment by naterush** [comment]
What's weird is that if I remove the startup file that runs and imports Mito, this is fixed for me!

**Comment by naterush** [comment]
Ok, run the following two code snippets in a notebook:
```
!rm ~/.mito/user.json
!cat ~/.mito/user.json
from importlib import reload  # Python 3.4+
reload(mitosheet)
mitosheet.sheet(analysis_to_replay="id-gaytsijwwh")
```

```
!rm ~/.mito/user.json
!cat ~/.mito/user.json
mitosheet.sheet(analysis_to_replay="id-gaytsijwwh")
```

In the second case, we get no signup flow, because the user.json does not exist. This is pretty much because the startup file imports the mitosheet package, which creates the user.json. But then we remove it, and when we go to import the mitosheet package again, it's already imported, so it doesn't run the init code (which is what creates the file). 

For some reason, in your video, the startup script is not creating the mitosheet. I don't know why this is, and I also can't figure out how to get the logs to debug it. 

The simplest fix is to just check if the user.json doesn't exist in the mitosheet.sheet call, and then add it there if it does not exist. I am going to get a PR up with this.

**Comment by naterush** [comment]
The exact specific set of steps I lay out above don't really explain why your video doesn't work, but I have a feel it's along the same lines (and that this fix will work), so check it out and let me know if it does!
