### ISSUE TITLE
display.max_rows stop working when mitosheet is installed into my jupyter lab

### ISSUE THREAD

**Issue by matabarestestiando** [mito-ds/monorepo#503]
**Describe the bug**
After installing mitosheet, display.max_rows option stop working.

**To Reproduce**
install mitoshhet
start a jupyter lab instance
create a new jupyter notebook
create sample dataframe

```
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))
```

Then trying to display it:

```
with pd.option_context('display.max_rows', 100, 'display.max_columns', 10):
    display(df)
```

not all rows are shown.

**Expected behavior**
All rows must be shown

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 mitoinstaller                     0.0.183
mitosheet                         0.1.449

**Comment by aarondr77** [comment]
Hey @matabarestestiando thanks for opening this issue. In order to display the `View in Mito` button when printing out dataframes, Mito sets the the `display.max_rows` option. 

If you want to set the `display.max_rows`, you can do so by running this command `python -m mitosheet turnondataframebutton` and then restarting your Jupyter Lab server.

**Comment by matabarestestiando** [comment]
Thanks. It works like a charm!

**Comment by matabarestestiando** [comment]
Closed!
